name: Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Copy to webroot
      run: cp public/. ${{ secrets.WEBROOT_PATH }}
